markdown: redcarpet
pygments: false
exclude: ['Gemfile', 'Gemfile.lock', 'package.json', 'Gruntfile.js', '.csscomb.json', 'node_modules']
title: 2014 Winfield Criterium
url: http://www.winfieldcriterium.com
author:
    name: Rich Johnson
    email: nixternal@gmail.com
    github: nixternal
    twitter: nixternal
version: 2014.1
github:
    repo: github.com/winfieldcriterium/winfieldcriterium.github.io
gems:
- jekyll-sitemap
