markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock', 'package.json', 'Gruntfile.js', '.csscomb.json', 'node_modules']
title: 2021 Winfield Criterium - Redirecting...
url: https://www.winfieldcriterium.com
enforce_ssl: www.winfieldcriterium.com
author:
    name: Rich Johnson
    email: rich@abdcycling.com.com
    github: nixternal
    twitter: nixternal
version: 2019.7.14
gems:
- jekyll-sitemap
